# Generated by Django 5.0 on 2024-01-02 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chanels', '0002_alter_chanel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=1000)),
                ('url', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='chanels.chanel')),
            ],
        ),
    ]
