# Generated by Django 5.0 on 2024-01-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_authors_video_liked_users_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
