# Generated by Django 5.0 on 2024-01-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_milestones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likes_milestones',
            field=models.IntegerField(default=0),
        ),
    ]
