# Generated by Django 5.0 on 2024-01-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_comment_likes_milestones_video_likes_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=11),
        ),
    ]
