# Generated by Django 5.0 on 2024-01-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
