# Generated by Django 5.0 on 2024-01-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanels', '0003_chanel_admins_chanel_owner_chanel_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='id',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
