# Generated by Django 5.0 on 2024-01-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanels', '0004_alter_chanel_id_alter_chanel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='subscribers_milestones',
            field=models.IntegerField(default=0),
        ),
    ]
