# Generated by Django 5.0 on 2024-01-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanels', '0005_chanel_subscribers_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='img',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
